library(shiny)
library(devtools)
install_github("satijalab/seurat", ref = "develop")
library(Seurat)
# library(SeuratData)
library(tidyverse)
library(shinythemes)
library(tidyverse)
library(htmltools)
library(bsplus)
library(plotly)
library(rsconnect)